In [1]:
import numpy as np
import pandas as pd
import nltk

In [2]:
from nltk.corpus import stopwords
import string

In [3]:
from google.colab import files
uploaded =files.upload()

Saving emails.csv to emails.csv


In [4]:
df = pd.read_csv('emails.csv')
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
df.shape

(5726, 2)

In [6]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [7]:
df.drop_duplicates(inplace = True)

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [9]:
def process_text(text):
  punc = [char for char in text if char not in string.punctuation]
  punc = ''.join(punc)
  clean_words = [word for word in punc.split() if word.lower() not in stopwords.words('english')]
  return clean_words

In [10]:
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
message = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(message, df['spam'], test_size=0.20, random_state=0)

In [13]:
from sklearn.naive_bayes import  MultinomialNB
classifier = MultinomialNB().fit(X_train, Y_train)

In [14]:
print(classifier.predict(X_train))
print(Y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [16]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(Y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_train, pred))
print()
print('Accuracy', accuracy_score(Y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3456
           1       0.99      1.00      0.99      1098

    accuracy                           1.00      4554
   macro avg       0.99      1.00      1.00      4554
weighted avg       1.00      1.00      1.00      4554


Confusion Matrix: 
 [[3443   13]
 [   2 1096]]

Accuracy 0.9967061923583662


In [18]:
print(classifier.predict(X_test))
print(Y_test.values)

[0 1 0 ... 0 1 1]
[0 1 0 ... 0 1 1]


In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(Y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_train, pred))
print()
print('Accuracy', accuracy_score(Y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3456
           1       0.99      1.00      0.99      1098

    accuracy                           1.00      4554
   macro avg       0.99      1.00      1.00      4554
weighted avg       1.00      1.00      1.00      4554


Confusion Matrix: 
 [[3443   13]
 [   2 1096]]

Accuracy 0.9967061923583662
